### ISSUE TITLE
[UI] 수정 패딩, 그림자, X버튼, BestScore 텍스트

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#109]
## ✏️ Description
수정된 디자인을 기반으로 UI를 수정합니다.

## ✅ Todo
- [ ] 버튼 및 디자인 요소 패딩값 조절
- [ ] 그림자 추가
- [ ] X 버튼 위치 수정 및 디자인 변경
- [ ] 게임 중 BestSocre 텍스트 추가
