### ISSUE TITLE
[Feat] 수정 버블껌 게임 ML 모델, 추가 은하수 게임 ML 모델

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#166]
## ✏️ Description
버블껌 게임의 음성 분류 모델과 예측 프로세스를 수정합니다.
은하수 게임 ML 모델파일을 추가합니다.

## ✅ Todo
- [x] 버블껌 게임 ML 모델 파일 변경
- [x] 버블껌 게임 Voice 분류 ML에 맞춰 음성 분류 Class값 수정
- [x] 은하수 게임 ML 모델 파일 추가
