### ISSUE TITLE
[Feat] 구현 StatisticView(데일리미션 + BestScore) 데이터 연결

### ISSUE THREAD

**Issue by chad0909** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#171]
## ✏️ Description

Star는 게임이 완료되면 연동하는걸로 하겠습니다.

## ✅ Todo
- [x] 데일리 연습 3가지 데이터 연동
- [x] 데일리 연습에 따른 Text 변화
- [x] Best Score 데이터 연동
