### ISSUE TITLE
[UI] 생성 별따먹기 StarGameView, StarTutorialView, StarPauseView, StarGameOverView 

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#181]
## ✏️ Description

별따먹기 게임, 일시정지, 종료화면을 임시로 그립니다.

## ✅ Todo
- [x] 별따먹기 GameView UI 생성
- [x] 별따먹기 GameTutorialView UI 생성
- [x] 별따먹기 GamePauseView UI 생성
- [x] 별따먹기 GameOverView UI 생성
