### ISSUE TITLE
[UI] 수정 기록뷰 UI 수정

### ISSUE THREAD

**Issue by MK827** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#199]
## ✏️ Description

기록뷰를 수정합니다.

## ✅ Todo
- [ ] 폰트 크기 및 색상 수정
- [ ] 문구 및 간격 조정
- [ ] font extension 수정(fontSize 11 -> 12)
- [ ] Color Asset 추가(ShadowBlue)
- [ ] BubbleGumBest, ChagokBest 이미지 교체
