### ISSUE TITLE
[Feat] 수정 디졸브방식 화면전환

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#251]
## ✏️ Description
트랜지션을 수정합니다.

## ✅ Todo
- [x] 버블게임 내 디졸브 화면전환 추가
- [x] 홈 > 버블 디졸브 화면 전환 수정
- [x] 홈 > 차곡 디졸브 화면 전환 수정
- [x] 홈 > 반짝 디졸브 화면 전환 수정
- [x] 홈 > 트로피 화면 전환 네비게이션으로 수정
