### ISSUE TITLE
[UI] 수정 ChagokGameView 레이아웃

### ISSUE THREAD

**Issue by MK827** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#271]
## ✏️ Description

ChagokGameView의 레이아웃을 수정합니다.

## ✅ Todo
- [ ] 게임뷰 컵스택 위치 조정(아래로)
- [ ] 게임뷰 Tap to Start 부분 그림자 추가
- [ ] 점수 Progress Bar 간격 조정
- [ ] 모래시계, Progress Bar 사이 간격 조정
- [ ] PauseView 버튼 이미지(홈) 사이즈 및 폰트 수정
