### ISSUE TITLE
[UI] 구현 GameOverView Prize 연결

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#307]
## ✏️ Description
GameOverView에 PrizeView 연결합니다.

## ✅ Todo
- [ ] PrizeView 레이아웃 수정
- [ ] PrizeView 포함한 프로젝트파일 추가
- [ ] GameOverView에 PrizeView 연결
