### ISSUE TITLE
[UI] 수정 ShopView 디자인 변경에 따른 레이아웃 수정

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#328]
## ✏️ Description
ShopView 레이아웃을 수정합니다.

## ✅ Todo
- [x] ShopView 레이아웃 수정(캐릭터 표시, 착용한 아이템 표시, 선택한 카테고리별로 해당하는 아이템 표시)
- [x] ShopView에서 쓰이던 이미지 중 코드로 대체 가능한 것들은 코드로 수정 (ShopView 버튼, 아이템 배경, 보유금액)
- [x]  Item.json 파일에서 카테고리 타입을 숫자에서 문자열로 변경
- [x] 착용 및 착용해제 기능 구현
