### ISSUE TITLE
[UI] 수정 ShopView UI, ShopView 캐릭터에 아이템 적용

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#337]
## ✏️ Description
ShopView UI를 수정합니다.

## ✅ Todo
- [x] 보유중, 착용중 라벨 수정
- [x] 구매 버튼 수정
- [x] 캐릭터에 아이템 적용
