### ISSUE TITLE
[Feat] 구현 HomeView에서 Item.json 파일 Fetch하도록 수정

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#344]
## ✏️ Description
이전에 ShopView에서 읽었던 것을 HomeView에서 아이템 파일을 읽어 게임에 적용되도록 합니다.

## ✅ Todo
- [x] HomeView에서 ShopItemViewModel Fetch하도록 수정
- [x] 하위뷰에서 ShopItemViewModel에 접근하도록 수정
- [x] ShopItemViewModel에 카테고리별로 장착한 아이템 저장되도록 수정, 저장된 값으로 뷰에 그리도록 수정
