### ISSUE TITLE
[FEAT] 추가 얼굴표정 5개 감지 및 텍스쳐 1:1 대응/ [Asset] 수정 Bubblegum 이미지 적용 문제 

### ISSUE THREAD

**Issue by Hyeneung-Kwon** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#53]
## ✏️ Description

5개 컵에 대응되는 각각의 얼굴 표정을 감지하고
표정과 컵 텍스쳐를 1:1로 대응시킵니다

## ✅ Todo
- [ ] 표정 5개 각각 감지
- [ ] 각각의 표정에 맞게 컵 텍스쳐 대응
- [x] Bubblegum 이미지 적용 문제
