### ISSUE TITLE
[Feat] 구현 BubbleGum 화면 이동

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#60]
## ✏️ Description
버블껌 게임의 상태에 따른 화면 이동을 구현합니다.
게임 도중 텍스트를 탭하면 다음 화면으로 전환되도록 임시로 구현합니다.

## ✅ Todo
- [ ] 게임 종료 트리거 생성
- [ ] 게임 종료시 Home 버튼 동작 구현
- [ ] 게임 종료시 Retry 버튼 동작 구현
