### ISSUE TITLE
[UI] 생성 BubbleGumView

### ISSUE THREAD

**Issue by MK827** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#7]
## ✏️ Description

BubbleGum게임 뷰를 생성합니다.

## ✅ Todo
- [x] BubbleGum게임 튜토리얼 커버 뷰 생성
- [x] BubbleGum게임 메인 뷰 생성
- [x] BubbleGum게임 일시정지 뷰 생성
- [x] BubbleGum게임 종료 뷰 생성
