### ISSUE TITLE
[UI] 생성 ChagokView, ChagokTutorialView, ChagokGameOverView

### ISSUE THREAD

**Issue by dayjack** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#8]
## ✏️ Description

차곡차곡 게임 관련 뷰를 기능없이 그립니다.

## ✅ Todo
- [ ] ChagokView 생성, UI 그리기
- [ ] ChagokTutorialView 생성, UI 그리기 
- [ ] ChagokGameOverView 생성, UI 그리기
