### ISSUE TITLE
[Feat] 구현 립트릴&텅트릴 사운드 분류

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#83]
## ✏️ Description
CreateML로 생성한 SoundClassification모델을 사용하여 사운드가 인식되면 게임이 시작되도록 구현합니다.

## ✅ Todo
- [ ] SoundClassification 모델 추가
- [ ] Record 권한 추가
- [ ] 사운드 인식된 경우 버블껌 게임 시작
- [ ] 사운드 인식이 Background로 분류된다면 게임 종료
