### ISSUE TITLE
[Feat] 구현 풍선껌 흔들리는 애니메이션, 난이도 조정에 따른 애니메이션 max값 재설정

### ISSUE THREAD

**Issue by JINi0S** [DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE#97]
## ✏️ Description
풍선껌 게임 진행 중 흔들리는 모션을 추가할 예정입니다.
UT 결과 평균 지속시간이 10초 안팍인 점을 고려하여 
풍선 확대 애니메이션의 최대값을 수정하여 빠르게 확대되는 모습을 볼 수 있도록 수정할 예정입니다. 
또한 애니메이션 설정을 easeInOut에서 easeOut으로 수정하여 초반에 빠르게 커지고 시간이 흐를수록 변화값이 적도록 합니다.

## ✅ Todo
- [x] 풍선껌 흔들리는 모션 구현
- [x] 난이도 조정에 따른 애니메이션 max값 재설정
- [x] 풍선 확대 애니메이션 설정 수정
